---
title: "An R package for Reactome Pathway Analysis"
author: 
- name: Guangchuang Yu
  email: guangchuangyu@gmail.com
  affiliation: Department of Bioinformatics, School of Basic Medical Sciences, Southern Medical University
date: "`r Sys.Date()`"
biblio-style: apalike
output:
  prettydoc::html_pretty:
    toc: true
    theme: cayman
    highlight: github
  pdf_document:
    toc: true
vignette: >
  %\VignetteIndexEntry{An R package for Reactome Pathway Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteDepends{org.Hs.eg.db}
  %\usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}
---






# Features

`ReactomePA` provides the following analysis and visualization functions for Reactome pathway enrichment:

## Enrichment Analysis

- `enrichPathway()`: Over-Representation Analysis (ORA) for Reactome pathways
- `gsePathway()`: Gene Set Enrichment Analysis (GSEA) for Reactome pathways
- `nsePathway()`: Network-based Set Enrichment Analysis (NSEA) using the Reactome reaction graph with Random Walk with Restart

## Post-hoc Analysis

- `bayes_reactome()`: Bayesian term selection to compress redundant pathway output
- `enrichPathway(weight = ...)` and `gsePathway(weight = ...)`: Weighted ORA/GSEA

## Utilities

- `gson_Reactome()`: Build a `GSON` gene-set annotation object from Reactome
- `prepareReactomeNetwork()`: Build and cache the Reactome reaction graph for NSEA

## Visualization

- `dotplot()`: Dot plot of enrichment results
- `cnetplot()`: Gene-concept network plot
- `emapplot()`: Enrichment map
- `heatplot()`: Gene-pathway heatmap
- `ridgeplot()`: Ridge plot of GSEA results
- `gseaplot()`: GSEA running score plot
- `viewPathway()`: Topological view of a Reactome pathway

# Full Vignette

Please go to <https://yulab-smu.top/biomedical-knowledge-mining-book/> for the full vignette.


# Citation

If you use `r yulab.utils::Biocpkg("ReactomePA")` [@yu_reactomepa_2016] in published research, please cite:

__*G Yu*__, QY He^\*^. ReactomePA: an R/Bioconductor package for reactome pathway analysis and visualization. __*Molecular BioSystems*__ 2016, 12(2):477-479. doi: [10.1039/C5MB00663E](http://dx.doi.org/10.1039/C5MB00663E)



# Need help?


If you have questions/issues, please post to [Bioconductor support site](https://support.bioconductor.org/) and tag your post with *ReactomePA*.

