---
date: 2017-07-24T00:11:02+01:00
title: Documentation
weight: 10
---


<link rel="stylesheet" href="https://guangchuangyu.github.io/css/font-awesome.min.css">


## <i class="fa fa-book"></i> Vignettes

+ <https://bioconductor.org/packages/devel/bioc/vignettes/ReactomePA/inst/doc/ReactomePA.html>

## <i class="fa fa-wordpress"></i> Blog posts

### <i class="fa fa-angle-double-right"></i> News and updates

+ [ReactomePA: an R/Bioconductor package for reactome pathway analysis and visualization](https://guangchuangyu.github.io/2016/02/reactomepa-an-r/bioconductor-package-for-reactome-pathway-analysis-and-visualization)
+ [BioC 3.1: NEWS of my BioC packages](https://guangchuangyu.github.io/2015/04/bioc-31-news-of-my-bioc-packages)
+ [BioC 3.2: NEWS of my BioC packages](https://guangchuangyu.github.io/2015/10/bioc-32-news-of-my-bioc-packages)
+ [BioC 3.3: NEWS of my BioC packages](https://guangchuangyu.github.io/2016/05/bioc-33-news-of-my-bioc-packages/)
+ [BioC 3.4: NEWS of my BioC packages](https://guangchuangyu.github.io/2016/10/bioc-34-news-of-my-bioc-packages)

### <i class="fa fa-angle-double-right"></i> Enrichment analysis

+ [functional enrichment for GTEx paper](https://guangchuangyu.github.io/2015/08/functional-enrichment-for-gtex-paper)
+ [functional enrichment analysis with NGS data](https://guangchuangyu.github.io/2015/08/functional-enrichment-analysis-with-ngs-data)
+ [leading edge analysis](https://guangchuangyu.github.io/2016/07/leading-edge-analysis/)
+ [why clusterProfiler fails](https://guangchuangyu.github.io/2014/08/why-clusterprofiler-fails)
+ [Comparison of clusterProfiler and GSEA-P](https://guangchuangyu.github.io/2015/11/comparison-of-clusterprofiler-and-gsea-p)

### <i class="fa fa-angle-double-right"></i> Visualization

+ [dotplot for enrichment result](https://guangchuangyu.github.io/2015/06/dotplot-for-enrichment-result)
+ [dotplot for GSEA result](http://guangchuangyu.github.io/2016/12/dotplot-for-gsea-result/)
+ [enrichment map](https://guangchuangyu.github.io/2014/08/enrichment-map)
+ [showCategory parameter for visualizing compareCluster output](https://guangchuangyu.github.io/2016/11/showcategory-parameter-for-visualizing-comparecluster-output/)


<i class="fa fa-hand-o-right"></i> Find out more on <https://guangchuangyu.github.io/tags/reactomepa>.

## <i class="fa fa-gift"></i> Workflow

+ [An end to end workflow for differential gene expression using Affymetrix microarrays](http://f1000research.com/articles/5-1384/v1)
+ [RNAseq workflow](https://github.com/twbattaglia/RNAseq-workflow)
